### ISSUE TITLE
doesn't work with multidplyr output

### ISSUE THREAD

**Issue by stanstrup** [tidyverse/broom#106]
Seems broom and multidplyr doesn't like each other for some reason.

```
library(dplyr)
library(broom)
library(multidplyr)

df.h = data.frame( 
  hour     = factor(rep(1:24, each = 21)),
  price    = runif(504, min = -10, max = 125),
  wind     = runif(504, min = 0, max = 2500),
  temp     = runif(504, min = - 10, max = 25)  
)
```

Compare the following

**Normal:**

```
dfHour = df.h %>% group_by(hour) %>%
  do(fitHour = lm(price ~ wind + temp, data = .))

dfHourCoef = tidy(dfHour, fitHour)
```

**with parallel do:**

```
dfHour_par = df.h %>% partition(hour) %>%
  do(fitHour = lm(price ~ wind + temp, data = .)) %>% 
  collect

dfHourCoef_par = tidy(dfHour_par, fitHour)
```

The last gives this error
-->

```
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
```

That is even if the objects on the surface look the same (apart from sorting):

```
all.equal(dfHour$fitHour[[7]],dfHour_par$fitHour[[1]])
```

-->

```
TRUE
```

**Comment by stanstrup** [comment]
Looks like a solution was already thought of: https://gist.github.com/dgrtwo/7d175bcc213aceaefd4f

Can we get this in the package?

**Comment by dgrtwo** [comment]
The reason for the bug is that multidplyr returns a grouped_df rather than a rowwise df. You could get the desired behavior with:

    dfHour_par %>%
        rowwise() %>%
        tidy(fitHour)

As for the draft solution for tidying party_df's (btw, note that the `col_name` function is also included in broom): the only reason I haven't put this in the package yet is that multidplyr is not yet in CRAN, so I'd rather not include it in the SUGGESTS (which I would need to include to use it in the examples). I suppose we could remove the examples for now and include it (solution doesn't actually call any multidplyr functions), but generally I like to avoid building with things that aren't officially released since the demand is fairly low, and since the tidier approach relies on some inner details of the `party_df` class that may well change before publication. This is definitely a priority once multidplyr is submitted to CRAN.

In the meantime, you could also do:

    dfHour_par = df.h %>% partition(hour) %>%
      do(fitHour = lm(price ~ wind + temp, data = .)) %>% 
      collect

**Comment by stanstrup** [comment]
Thanks for the extensive explanation. Using `rowwise()` does work.

I didn't get what you meant by the last snippet that was the one that now throws an error.

**Comment by alexpghayes** [comment]
Closing since data frame tidiers have been deprecated.
