### ISSUE TITLE
Testing the 'broom' package

### ISSUE THREAD

**Issue by mbojan** [tidyverse/broom#146]
The package contains almost 100 `tidy` methods for objects that come from a large number of packages. Testing requires installation of all these new packages. This is cumbersome because if I just add yet another `tidy` method it is totally independent of 95% of the rest of the code.

As demonstrated by the TravisCI error at this very moment, testing fails because one of the many external packages that provide classes that "broom" is `tidy`ing fails to install for one reason or another.

I think in general it would be useful to be able to switch off selected tests, e.g. for methods that are not being  worked-on. Alternatively, in the long term, it might be worth considering splitting the "broom" package into sub-packages. Each sub-package might correspond to a certain external package (e.g. "broom-survival" and so on). Broom might then provide definitions for generics `tidy`, `glance`, etc. with the actual methods elsewhere. I am affraid that with the current mode of operation "broom" will quickly become unmaintainable...

**Comment by dgrtwo** [comment]
This is a problem that was faced by the caret package as well [here's some slides on how they addressed it](http://www.slideshare.net/Work-Bench/nobody-knows-what-its-like-to-be-the-bad-man).

I don't want to turn off tests in general, because tests are one of the few ways we can detect changes in these many packages that cause tidiers to fail. (Our test coverage is already too low). And even if we turned them off using a code switch, we would still have to leave them in Suggests (unless we removed both the tests and example code), at which point they'll be installed anyway.

There are two cases where we've begun spreading out tidying methods into other packages: the [tidytext](https://github.com/juliasilge/tidytext) package is where methods for text data (e.g. tm and quanteda) go, and the [biobroom](http://bioconductor.org/packages/release/bioc/html/biobroom.html) package is for Bioconductor objects. In each case someone else is the primary maintainer, which also helps take the strain off me, so I imagine that will be true of others we split off. I'm not entirely sure a package just for survival methods would be worth splitting off but I can imagine other subsets doing so.

**Comment by lselzer** [comment]
There's also an issue with writing test for some conflicting packages `gam` and `mcgv`. Whichever gets loaded first conflict with the later making tests unusable. I searched for solutions but I found none except reloading R which is not a solution in this case.

**Comment by mbojan** [comment]
@lselzer don't attach the package with `require` or `library`, just load the namespace with `loadNamespace` or `requireNamespace` and then refer to package functions with `::`.

**Comment by mbojan** [comment]
@dgrtwo 

> I don't want to turn off tests...

Sure, that's what the tests are for. Let Travis run all of them. What I meant is perhaps to have an option for the tests to continue in case of some of the external packages fail to install or are not available. It would be convenient for local development. Although perhaps just executing selected testthat scripts manually is the way to go...

> This is a problem that was faced by the caret package...

Thanks. Impressive solution. I can imagine that this testing framework took not less work than the package itself... ;)

Splitting is a good idea. `survival` was just an example, even though there are not one but three classes  to tidy.

**Comment by alexpghayes** [comment]
Getting the Travis builds to actually go through would be a good thing to do this summer. I'm a bit out of my depth on this one. @topepo have any suggestions based on `caret` experiences?

**Comment by karldw** [comment]
@alexpghayes, would [Michael Rutter's pre-compiled packages](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u) be helpful?

**Comment by topepo** [comment]
I agree with @karldw . Go through and specify as many packages as you can. [Here](https://github.com/topepo/embed/blob/master/.travis.yml) is an example of one that I had that was timing out.

**Comment by alexpghayes** [comment]
This has been partially addressed in #360, which gets Travis builds to complete for R 3.4, 3.5, 3.6. Closing since splitting `broom` is being dealt with elsewhere, and will open a new issue on getting Travis to build for R 3.1, 3.2, 3.3.
