### ISSUE TITLE
broom functions should return tibble objects and not not `data.frame`

### ISSUE THREAD

**Issue by jlegewie** [tidyverse/broom#150]
`broom` builds on Hadley Wickham ideas and I think should be in line with his packages. They pretty all now use `tibble` objects and not `data.frame`. Here are more infos about tibble's:
https://github.com/hadley/tibble

**Comment by dgrtwo** [comment]
This is 100% in the plans for broom this summer. It's just a fairly substantial task

**Comment by alexpghayes** [comment]
This is a great point, and definitely a behavior that I'd like to have in `broom`.

We're going to submit `broom 0.5.0` to CRAN on July 2nd, and at that point all tidiers will *return* tibbles.

However, this behavior is still going to be an issue at least for the upcoming release. This is because most tidying methods use `data.frame`s in the internals, and in many cases the next release just coerces this to a `tibble` before returning. Changing the tidier internals is more difficult than changing the return type, however, so this is a ways out still.

I'm going to add this to the to-do list for the broom release after `0.5.0`.

**Comment by alexpghayes** [comment]
Broom tidiers now use tibbles. More information at https://broom.tidyverse.org/news/. Broom 0.5.0 will be submitted to CRAN on Monday.
