### ISSUE TITLE
include model specification in tidied model object

### ISSUE THREAD

**Issue by dschneiderch** [tidyverse/broom#152]
from the git documentation:

> We avoid including arguments that were given to the modeling function. For example, a glm glance output does not need to contain a field for family, since that is decided by the user calling glm rather than the modeling function itself.

It would actually be really convenient if model objects included the model specification. e.g. when you are comparing which model type/family/link works best.

**Comment by alexpghayes** [comment]
Where would you want this to do? In `glance`? I'd be a fan of that.

If we did do this, we'd probably want to implement this for `glm`, `gam` and friends, the mixed modelling packages, etc.

**Comment by alexpghayes** [comment]
Since yesterday I've learned the current approach is that glance shouldn't contain information from the original function call (i.e. arguments passed to a modelling function, or the name of the function itself). Closing in light of that. If this forces you to use a particularly painful workflow, let me know and we'll see if we can work something out.

See also #189.
