### ISSUE TITLE
df in glance() output too big by 1?

### ISSUE THREAD

**Issue by evodevosys** [tidyverse/broom#196]
glance() for lm gives one column that is df and one column that is df.residual.  The df column is one more than the df for the model terms:  

try:

`> summary(lm(mpg~disp,data=mtcars))`

which gives:

`F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10`

versus

`> glance(lm(mpg~disp,data=mtcars))`

which gives df=2 and df.residual=30

is this an error or does the df in glance() mean something different?

**Comment by dgrtwo** [comment]
The df column counts the intercept as a degree of freedom, while the F-test does not, because by default the F-test compares the model to a just-intercept model. (That's why `1 and 30` doesn't add up to the number of observations).

Each have their uses and can be extracted directly from the regression summary output. However, the model does use two degrees of freedom- try doing `summary(lm(mpg~disp,data=mtcars))$df`, or change it to `mpg~0+disp` to try the model without an intercept.
