### ISSUE TITLE
Feature request: glmnet multinomial

### ISSUE THREAD

**Issue by nsonneborn** [tidyverse/broom#222]
It would be great to see broom capabilities on `glmnet` output with `family="multinomial"`. Other glmnet outputs are supported by `tidy()`

**Comment by erleholgersen** [comment]
I was going to give this a shot, but I think it's actually a bug rather than a new implementation?

There's already support for `tidy()` on `family = 'multinomial'`,  but the resulting data frame has a lot of `NA`'s.  Looking at the code, I think the issue is this part in `glmnet_tidiers.R`.
``` r 
  if (inherits(x, "multnet")) {
    beta_d <- plyr::ldply(beta, function(b) {
      fix_data_frame(as.matrix(b), newcol = "term")
    }, .id = "class")
    ret <- beta_d %>% tidyr::gather(step, estimate, -term, -class)
  } else {
    beta_d <- fix_data_frame(as.matrix(beta), newnames = 1:ncol(beta), newcol = "term")
    ret <- tidyr::gather(beta_d, step, estimate, -term)
  }
```

For the multinomial implementation, `fix_data_frame(as.matrix(b), newcol = "term")` is missing the `newnames` argument. It returns a data frame with column names `s1`, `s2`, etc., which results in `NA`s when they're attempted converted to numeric in the following `mutate()` call.

Anyways, I can submit a pull request for this – just wanted to make sure I understand the problem!

**Comment by alexpghayes** [comment]
Yep, it's a bug fix rather than a new implementation. A PR would be fantastic!
