### ISSUE TITLE
Update https://github.com/tidyverse/broom list

### ISSUE THREAD

**Issue by Moddbo** [tidyverse/broom#277]
I think you have tidy functions for topicmodels, including DocumentTermMatrix. Might want to update the list.

**Comment by alexpghayes** [comment]
Good catch! I believe these live in `tidytext`, which is why they don't show up in the available methods vignette. The vignette is generated automatically based on methods exported by `broom`. We should be catching most of the supported tidiers in that vignette (I hope).

Let me know if you find anything else that's missing!
