### ISSUE TITLE
broom::tidy isn't working with within-subject ANOVA outputs

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/broom#299]
Hi, I am working with the latest version of broom (`0.4.4`) and having an issue while getting the tidy output. Here is a fully reproducible example:

``` r
# loading the necessary libraries
library(tidyverse)

# converting the iris dataset to long format
iris_long <- datasets::iris %>%
  dplyr::mutate(.data = ., id = dplyr::row_number(x = Species)) %>%
  tidyr::gather(
    data = .,
    key = "condition",
    value = "value",
    Sepal.Length:Petal.Width,
    convert = TRUE,
    factor_key = TRUE
  ) %>%
  tidyr::separate(
    col = "condition",
    into = c("attribute", "measure"),
    sep = "\\.",
    convert = TRUE
  ) %>%
  tibble::as_data_frame(x = .)

# specifying the model
iris.mod <-
  stats::aov(formula = value ~ attribute * measure + Error(id / (attribute * measure)),
             data = iris_long)

# checking the summary
summary(iris.mod)
#> 
#> Error: id
#>           Df Sum Sq Mean Sq F value Pr(>F)
#> Residuals  1    264     264               
#> 
#> Error: id:attribute
#>           Df Sum Sq Mean Sq
#> attribute  1  237.2   237.2
#> 
#> Error: id:measure
#>         Df Sum Sq Mean Sq
#> measure  1   1114    1114
#> 
#> Error: id:attribute:measure
#>                   Df Sum Sq Mean Sq
#> attribute:measure  1 0.7993  0.7993
#> 
#> Error: Within
#>                    Df Sum Sq Mean Sq  F value Pr(>F)    
#> attribute           1  470.1   470.1 1445.988 <2e-16 ***
#> measure             1   57.7    57.7  177.458 <2e-16 ***
#> attribute:measure   1    1.5     1.5    4.725 0.0301 *  
#> Residuals         592  192.5     0.3                    
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# tidying the ouput
broom::tidy(iris.mod)
#> Error in if (attr(object$terms, "intercept")) table <- table[-1, ]: argument is of length zero
```

Created on 2018-04-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mvevans89** [comment]
@alexpghayes I'm willing to take a stab at this!

**Comment by alexpghayes** [comment]
Awesome! You'll want to start by forking the broom repository, and then cloning it to your computer. Once you have it on your local computer, you'll want to take a look at `tidy.aovlist` in `R/anova_tidiers.R`, editing the code until you get it to work the way that you want. Let me know if I can help.

Be sure to [change the documentation](http://r-pkgs.had.co.nz/man.html) so that it accurately describes the new behavior.

Then next step will be to [write a test](http://r-pkgs.had.co.nz/tests.html) to make sure the error in the reprex above has been resolved. You create a file `tests/testthat/test-anova.R` and put the test in there.

Once the tests are passing, the final step is to commit all your work to your fork, and then open a pull request to `broom`.

A good general reference is Hadley Wickham's book R Packages, which I've linked to above. It's easy to get information overload, so just drop me a question anytime!
