### ISSUE TITLE
To drop NAs or not to drop NAs

### ISSUE THREAD

**Issue by alexpghayes** [tidyverse/broom#324]
Several bugs or inconsistent behaviors are related to dropping rows containing `NA` values (#166, #241, #307). We need to:
- [ ] Decide whether rows contain `NA` should continue to be silently dropped
- [ ] Check for consistent behavior across tidiers

**Comment by dgrtwo** [comment]
I think rows that have nothing besides NA in tidy outputs, e.g. from lm, should be dropped (they always have been in broom and in the result of coef(summary(x)) for those models).

As commented in #241, since there's a bit of useful information in the MANOVA row that should never have been dropped (mistake) so that should be changed back (let's make sure to add it to NEWS since it's technically a breaking change).

The confint issue is then just a bug that can be fixed in confint_tidy.
