### ISSUE TITLE
NULL value in available-methods.Rmd vignette

### ISSUE THREAD

**Issue by briatte** [tidyverse/broom#379]
The [available methods vignette](https://github.com/tidyverse/broom/blob/master/vignettes/available-methods.Rmd) returns a row labelled `NULL`

Slightly modifying the code of the vignette to show the problematic line:

```r
library(broom)
library(dplyr)
library(stringr)

method_df <- function(method_name) {
  m <- as.vector(methods(method_name))
  tibble::tibble(class = str_remove(m, str_c(method_name, "[.]")),
                 !!method_name := "x")
}

method_df("tidy") %>% 
  left_join(method_df("glance"), by = "class") %>% 
  left_join(method_df("augment"), by = "class") %>% 
  mutate_all(tidyr::replace_na, "") %>% 
  dplyr::filter(class == "NULL")
```

returns

```
# A tibble: 1 x 4
  class tidy  glance augment
  <chr> <chr> <chr>  <chr>  
1 NULL  x     x      x    
```

The problem arises because `methods()` returns `function.NULL*` in its vector of results.

An easy fix to avoid users thinking that there is a class of models called `NULL`:

```r
method_df("tidy") %>% 
  left_join(method_df("glance")  , by = "class") %>% 
  left_join(method_df("augment") , by = "class") %>% 
  mutate_all(tidyr::replace_na, "") %>% 
  dplyr::filter(class != "NULL")
```

**Comment by alexpghayes** [comment]
Thanks for bringing this up. `broom` does export `tidy.NULL`, `glance.NULL` and `augment.NULL`, all of which return an empty tibble. Most of the time it isn't important, but it can useful when `map_dfr`ing over named elements of a list or similar.

I see how this could be confusing, but I'd like to leave this in the documentation mostly for people on the development side of things. I hope that our users know that `NULL` is not a model, but I don't think including it in the documentation will be detrimental, because even if they do, they aren't going to be using `tidy.NULL`.

I did just notice that `augment.NULL` and `glance.NULL` aren't documented, so a good next step is probably to document them. There'll be a documentation overhaul at some point this summer, but it's currently a little bit out.

**Comment by briatte** [comment]
Makes sense, thanks!
